### Интеллектуальные системы, МТУСИ

#### Лабораторная работа 1

#### Выполнил :   Семенов А.И.

#### Группа:   ЗМБД2032

# 1.Print 'Hello HCIA'.

In [1]:
print("Hello HCIA")

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a = 70
b = 130
print( a + b)

200


# 3.Define a list and replicate in three different ways.

In [20]:
my_list = [1,2,3,4,5,6]

# копирование с помощью метода copy()
copy_list_1 = my_list.copy()
print("Копия списка #1:", copy_list_1)

# копирование с помощью среза
copy_list_2 = my_list[:]
print("Копия списка №2:", copy_list_2)

# кпопирование с помощью функции list()
copy_list_3 = list(my_list)
print("Копия списка №3:", copy_list_3)

# генератор списков медленно
copy_list_4 = [i for i in my_list]
print("Копия № 4 :", copy_list_4)

#  с помощью метода extend() - добавляет в конец списка элементы
copy_list_5 = []
copy_list_5.extend(my_list)
print("Копия № 5:", copy_list_5)

Копия списка #1: [1, 2, 3, 4, 5, 6]
Копия списка №2: [1, 2, 3, 4, 5, 6]
Копия списка №3: [1, 2, 3, 4, 5, 6]
Копия № 4 : [1, 2, 3, 4, 5, 6]
Копия № 5: [1, 2, 3, 4, 5, 6]


# 4.Define two lists and merge them together.

In [22]:
# конкатенация списков\
list_1 = [1,2,3,4,5]
list_2 = [6,7,8]
merge_list = list_1 + list_2
print(merge_list)

[1, 2, 3, 4, 5, 6, 7, 8]


# 5. Get the last element of the list and print it.

In [23]:
mylist = [1,2,3,4,5]
print("Последний элемент списка:", mylist[-1])

Последний элемент списка: 5


# 6.Define a tuple that contains only one element.
- Having one element within parentheses is not enough. We will need a trailing comma to indicate that it is, in fact, a tuple.

In [33]:
# для создания кортежа одного элемента недостаточно, необходимо использовать конечную запятую
my_tuple = (1,)
print(type(my_tuple))
print(my_tuple)

<class 'tuple'>
(1,)


# 7.Define a three-line long string.
- непонято что имеется ввиду
- a backslash ( \ ) is a continuation character, and if it is placed at the end of a line, it is considered that the line is continued, ignoring subsequent newlines.

In [57]:
semenov_string = """Huawei certification
Huawei certification
Huawei certification""" 

print(type(semenov_string))
print(semenov_string)


my_string =("Huawei certification " 
            "Huawei certification " 
            "Huawei certification" )

print(my_string)
print(type(my_string))

<class 'str'>
Huawei certification
Huawei certification
Huawei certification
Huawei certification Huawei certification Huawei certification
<class 'str'>


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [59]:
semenov_tuple = (1,3,4,6 , 'a', 'b', [12,4,56])

for i in semenov_tuple:
    print(i)

1
3
4
6
a
b
[12, 4, 56]


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [60]:
def mul(a, b):
    return a * b

mul(8,6)
    

48

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.
 - zeros. Return a new array setting values to zero.
 - zeros_like. Return an array of zeros with shape and type of input.
 - numpy.reshape(a, newshape, order='C')Gives a new shape to an array without changing its data. позволяет задавать форму числами, а не кортежем чисел. Однако, если вам необходимо передавать форму в виде кортежа, то придется использовать numpy.reshape().


In [70]:
import numpy as np
# используя метод zeros, возвращает нулевой заданный масиив
semenov_array = np.zeros(( 5, 5))
print(semenov_array)


# с помощью zeros_like() , возвращает нулевой массив на основе  выбранного массива 

my_array = np.arange(25)
my_array = my_array.reshape((5, 5))

np.zeros_like(my_array)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.
 - numpy.arange( [ start , ] stop , [ step , ] dtype = None , * , like = None ). Возвращает равномерно распределенные значения в заданном интервале. Значения генерируются в пределах полуоткрытого интервала (другими словами, интервала, включая начало, но исключая остановку ). Для целочисленных аргументов функция эквивалентна встроенной функции диапазона Python , но возвращает ndarray, а не список.

In [81]:
import numpy as np
zero_array = np.zeros((4,6))
print("Массив с нулевыми элементами:", zero_array)

# с помощью reshape
semenov_array = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
semenov_array = semenov_array.reshape((4,6))
print("Вариант 2:", semenov_array)

# с помощью zeros_like and reshape
semenov_array = np.arange(24)
semenov_array = semenov_array.reshape((4,6))
print("Вариант 3:", np.zeros_like(my_array) )

Массив с нулевыми элементами: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Вариант 2: [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Вариант 3: [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [91]:
import numpy as np

# используем reshape
semenov_array = np.arange(15)
semenov_array = semenov_array.reshape((3,5))

print(semenov_array)
semenov_array.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(3, 5)

# 13.Define two matrices, then calculate and print the result of their point multiplication.
 - numpy.matmul( x1 , x2 ). Матричное произведение двух массивов.
 - numpy.dot( a , b , out = Нет ). Точечное произведение двух массивов. Конкретно, 
  * Если и a, и b являются одномерными массивами, это внутреннее произведение векторов (без комплексного сопряжения).
  * Если и a, и b являются двумерными массивами, это умножение матриц, но использование matmulили является предпочтительным.

In [2]:
import numpy as np

matrice_1 = np.arange(16).reshape((4,4))
matrice_2=np.arange(16, 32, 1).reshape((4,4))

mul_mat = np.matmul(matrice_1, matrice_2)
print(mul_mat)

# с помощью np.dot()
mul_mat_2 = np.dot(matrice_1, matrice_2)
print(mul_mat_2)

[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]
[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]
